### ISSUE TITLE
Failing to install

### ISSUE THREAD

**Issue by yrashk** [douglascamata/setup-docker-macos-action#1]
```
==> Pouring python@3.10--3.10.9.monterey.bottle.tar.gz
Error: The `brew link` step did not complete successfully
```

https://github.com/omnigres/omnigres/actions/runs/3851338812/jobs/6562403799#step:3:445

I am trying to figure out if there's an easy way to fix this.

**Comment by yrashk** [comment]
Setting HOMEBREW_NO_INSTALLED_DEPENDENTS_CHECK may have helped:

https://github.com/omnigres/setup-docker-macos-action/commit/e1110b0c2b6752fb773fc71b529fc0a63313ec04

**Comment by douglascamata** [comment]
Good find regarding `HOMEBREW_NO_INSTALLED_DEPENDENTS_CHECK`! In fact, I was working on a rewrite into Typescript action (to be able to dynamically cache more things and reduce build time, which is important to save us free and paid CI minutes) at https://github.com/douglascamata/setup-docker-macos-action/tree/convert-to-javascript-action and I had this option set there. 

I think it's fair enough to set this env var here too for now. I have to review the work on that other branch and release it as beta soon.

**Comment by douglascamata** [comment]
@yrashk it should be fixed now. I updated the `v1-alpha` tag. Can you please try it out and let me know if it works for you?

**Comment by douglascamata** [comment]
@yrashk as I see that you started using the action again, I assume the bug is solved. Thanks for the report and feel free to reopen in case the bug's still there. 🙇
