### ISSUE TITLE
Colima github action breaking

### ISSUE THREAD

**Issue by commjoen** [douglascamata/setup-docker-macos-action#10]
Dear awesome @douglascamata ,
thank you so much for this great github action! We have been actively using it in OWASP WrongSecrets as we wanted to validate whether our container would work in Colima.
Now we have hit a bit of a problem: Our Github action has started to fail: https://github.com/OWASP/wrongsecrets/actions/runs/5887533972/job/15967077575
With the error found at https://github.com/OWASP/wrongsecrets/actions/runs/5887533972/job/15967077575#step:3:63:
`cat: /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/colima.rb: No such file or directory` . Can you help us good sir? What can we do to fix this?

**Comment by douglascamata** [comment]
Thanks for the report, @commjoen. I'm on a bit of a short, half-vacations week, but I will have a look as soon as I can. 

In the meantime, can you try to upgrade to the [v1-alpha.5](https://github.com/douglascamata/setup-docker-macos-action/releases/tag/v1-alpha.5) tag to see whether it fixes your issue or not?

**Comment by commjoen** [comment]
Enjoy your vacation sir! No rush ;-), we know OSS takes time and are grateful for your work! Upgrading to it did not work, see https://github.com/OWASP/wrongsecrets/actions/runs/5889098046/job/15971584677?pr=939

**Comment by douglascamata** [comment]
Apparently it was a quick one, @commjoen. Can you please try the tag `v1-alpha.6`? If that works well I will update the `v1-alpha` tag too.

**Comment by yrashk** [comment]
I ran into this as well,  had the same error (`cat: /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/colima.rb: No such file or directory`), upgraded and now I am getting `cat: docker: Is a directory`

**Comment by yrashk** [comment]
It looks like my error is happening because my project has `docker` directory in the root.

**Comment by yrashk** [comment]
I've sent a workaround in #11

**Comment by commjoen** [comment]
V1-alpha.6 seems to work!

**Comment by commjoen** [comment]
Merging the usage of `v1-alpha.6` to master \o/ thank you! I am fine with closing the issue now :) .

**Comment by commjoen** [comment]
Hmm the issue seems to be back: our Colima builds keep on failing as visible at https://github.com/OWASP/wrongsecrets/actions/runs/6004614599/job/16285572865?pr=949

**Comment by douglascamata** [comment]
That's yet a new issue. I've been tracking it on #16 as the root cause is different. Let's move this over there, please.
