### ISSUE TITLE
Docker does not expose ports as described in docker-compose

### ISSUE THREAD

**Issue by limpbrains** [douglascamata/setup-docker-macos-action#23]
Hi

This issue is probably not related to this actions, but I don't know for sure.

I noticed that my github actions started to failing recently, because `docker-compose up` does not expose port.
I was able to ssh to runner and checked that docker runs fine, and all the containers.
After I executed `colima restart` a few times port finally was open.

I think issue might be related with some new colima version. 
It would be nice if I could specify which colima version I want to use when configuring the action.

Many thanks!

**Comment by douglascamata** [comment]
I believe this could have been fixed by #22 too. Do you mind trying the feature it introduces?

**Comment by douglascamata** [comment]
Or if you could help narrow down which version of Colima introduced the problem, it would be great to open a bug report on Colima and document it here.

**Comment by limpbrains** [comment]
Thx, #22 solved my problem, closing this ticket
