### ISSUE TITLE
How's performance inside Docker for you people?

### ISSUE THREAD

**Issue by Luc45** [douglascamata/setup-docker-macos-action#30]
I couldn't extract a 25mb .tar.gz file inside Docker in 5 minutes. Is this normal? How's performance inside the container for you?

_(PS: I thought about moving this to Discussions, but who read discussions anyway?)_

**Comment by douglascamata** [comment]
Can you provide logs? While this action does the setup of the tools, I cannot support the tools themselves. But in general, if you aren't able to extract a 25mb file it's a sign that you have other issues.

**Comment by Luc45** [comment]
@douglascamata Sorry about the delay in getting back to you, it's been a while since I tried this out and I don't remember the details.

I tried playing with the resources allocated to the VM a bit, instead of allocating all CPU cores I did like $all-1 to have some leeway for the OS, things like that.

I remember this improved things a bit, but the underlying reason for my performance issues was something else in my script that I don't remember right now.

I'll be closing this issue now, feel free to reopen if needed. Thanks!
