### ISSUE TITLE
Error installing QEMU with `brew`: failing to link `python` (required by `qemu` formula)

### ISSUE THREAD

**Issue by owenthereal** [douglascamata/setup-docker-macos-action#31]
Build link: https://github.com/pgxman/pgxman/actions/runs/8226570015/job/22524288851#step:3:269

Logs:

```
  ==> Installing qemu dependency: python@3.12
  ==> Downloading https://ghcr.io/v2/homebrew/core/python/3.12/manifests/3.12.2_1
  Already downloaded: /Users/runner/Library/Caches/Homebrew/downloads/db6a7027cff95a641d6d0c07e00f7b8fa26b0733b6d215c3752b745a381ebcb8--python@3.12-3.12.2_1.bottle_manifest.json
  ==> Pouring python@3.12--3.12.2_1.ventura.bottle.tar.gz
  Error: The `brew link` step did not complete successfully
  The formula built, but is not symlinked into /usr/local
  Could not symlink bin/2to3
  Target /usr/local/bin/2to3
  already exists. You may want to remove it:
    rm '/usr/local/bin/2to3'
  
  To force the link and overwrite all conflicting files:
    brew link --overwrite python@3.12
  
  To list all files that would be deleted:
    brew link --overwrite python@3.12 --dry-run
  
  Possible conflicting files are:
  /usr/local/bin/2to3 -> /Library/Frameworks/Python.framework/Versions/3.12/bin/2to3
  /usr/local/bin/2to3-3.12 -> /Library/Frameworks/Python.framework/Versions/3.12/bin/2to3-3.12
  /usr/local/bin/idle3 -> /Library/Frameworks/Python.framework/Versions/3.12/bin/idle3
(...)
```

</p>
</details>

**Comment by douglascamata** [comment]
@FHachez I will take some time today to see whether other people using Homebrew are having this issue. 

I personally never encountered it myself and I use macOS full time, with qemu. 

This make me wonder wether it's Github that when building the Action Runner's images links the system Python into `/usr/local/bin`, I think it's safe to override it. In this case we can merge your PR and see how it goes.

**Comment by douglascamata** [comment]
FYI we are trying to figure out a good way of handling this. 🚧

**Comment by douglascamata** [comment]
Meanwhile, I reported this as a bug to Github as it doesn't happen in all runner versions: https://github.com/actions/runner-images/issues/9510.

**Comment by douglascamata** [comment]
For those using this action directly from the `main` branch: I just merge a PR with a fix for the Python issue. Can you please test it and let me know if it works for you too? After confirmation I'll push a new release.

**Comment by FHachez** [comment]
Awesome, thank you, @douglascamata. It's working for us on the github actions.

**Comment by humdrum** [comment]
It's working for me too. Thank you. @douglascamata

**Comment by GlassOfWhiskey** [comment]
THis is working also with StreamFlow (see alpha-unito/streamflow#408)

**Comment by douglascamata** [comment]
I pushed a new `v1-alpha.13` tag and updated the `v1-alpha` tag with the fix. 

I'll leave this issue open for a week in case something else comes up as a consequence of the workaround. If nothing comes up by next Monday I will close this issue.

Thx to everyone involved and have a great week!

**Comment by douglascamata** [comment]
No more issues reported, so I'm closing this. Thanks again to everyone that helped in some way. 🙇
