### ISSUE TITLE
verified in the GitHub Marketplace

### ISSUE THREAD

**Issue by kevinjqliu** [douglascamata/setup-docker-macos-action#36]
Is it possible to have this action be "verified in the GitHub Marketplace"? 

There's currently a policy to block using unverified actions.
![Screenshot 2024-09-12 at 10 55 30 PM](https://github.com/user-attachments/assets/719fcbe5-cb8d-4b25-8f11-16ec4312cfa5)

**Comment by douglascamata** [comment]
@kevinjqliu only certain creator that have a relationship with Github will get "verified" on the Github Marketplace. I am not one of those. There's no way for a random person to get their action verified.

**Comment by douglascamata** [comment]
See https://github.com/orgs/community/discussions/25265.
