### ISSUE TITLE
Use preinstalled Colima

### ISSUE THREAD

**Issue by pwltr** [douglascamata/setup-docker-macos-action#5]
Colima comes preinstalled with the MacOS runner image as of [this PR](https://github.com/actions/runner-images/issues/6216). It may make sense to avoid installing it separately in this action.

**Comment by douglascamata** [comment]
@pwltr Colima is managed by Homebrew in both cases. It won’t be reinstalled if not needed. It just might be upgraded is there is a more recent version. This is not a problem.

**Comment by pwltr** [comment]
Yes, this seems to be the case. There was no noticeable difference in run time when going from manual setup (docker + docker-compose only) to this action.
